language: php
dist: trusty
php:
- 5.6
- 7.0
- 7.1
- 7.2
- nightly
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache"
env:
- COMPOSER_NO_INTERACTION=1
install:
- travis_retry composer install --no-scripts --no-suggest
script:
- composer validate --strict
- find Components Controllers Resources Views Mollie.php '*.php' | xargs -n 1 -P4 php -l
